spring.application.name=FujitsuDeliveryFeeCalculator

# H2
spring.datasource.url=jdbc:h2:file:./data/deliverydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 'update' = create tables on first run, leave data alone on subsequent runs
spring.jpa.hibernate.ddl-auto=update

# H2 browser console at http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Weather import cron every 15 min
weather.import.cron=0 15 * * * *

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html